# 登录相关
@baseUrl = http://localhost:3000
# @name  getKey
GET  {{baseUrl}}/login/qr/key

###
# @name createQr
GET  {{baseUrl}}/login/qr/create?key=62ec25bb-bdea-46ab-80c8-2f39f5fb56f4?&qrimg=true

###
# @name  homepage
GET {{baseUrl}}/homepage/block/page HTTP/1.1

###
GET {{baseUrl}}/personalized?limit=10 HTTP/1.1